import type {Metadata} from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import React from "react";


export const metadata: Metadata = {
    title: "Create TVO App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={"bg-[#333A43]"}>
        <body className={" w-screen flex justify-center py-10 bg-[#333A43]"}>
        <div className={"lg:w-[700px] w-screen "}>
            <header>
                <NavBar/>
            </header>
            <main>
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
